/*
@TargetNode='AzureArcConfig'
@GeneratedBy=DesmondAdmin
@GenerationDate=09/18/2023 14:09:26
@GenerationHost=SG-00194
*/

instance of DSC_Firewall as $DSC_Firewall1ref
{
SourceInfo = "::10::13::Firewall";
 Enabled = "True";
 Ensure = "Present";
 ModuleName = "NetworkingDsc";
 Authentication = "Required";
 ModuleVersion = "9.0.0";
 Name = "Public";
 DisplayName = "Enable RDP";
 Protocol = "TCP";
 ResourceID = "[Firewall]Enable_RDP";
 Encryption = "Required";
 RemotePort = {
    "3389"
};
 Direction = "Inbound";
 InterfaceType = "RemoteAccess";
 Action = "Allow";
 Description = "Opens port 3389 to allow a remote user to RDP into the machine";
 ConfigurationName = "AzureArc";
};
instance of OMI_ConfigurationDocument

                    {
 Version="2.0.0";

                        MinimumCompatibleVersion = "1.0.0";

                        CompatibleVersionAdditionalProperties= {"Omi_BaseResource:ConfigurationName"};

                        Author="DesmondAdmin";

                        GenerationDate="09/18/2023 14:09:26";

                        GenerationHost="SG-00194";

                        Name="AzureArc";

                    };
