/*
@TargetNode='localhost'
@GeneratedBy=DesmondAdmin
@GenerationDate=11/01/2023 11:17:44
@GenerationHost=SG-00194
*/

instance of DSC_Computer as $DSC_Computer1ref
{
Description = "A server to test funtionality of Azure Arc";
 ModuleVersion = "9.0.0";
 ModuleName = "ComputerManagementDsc";
 Name = "Azure Arc Test Server";
 ResourceID = "[Computer]NewName";
 SourceInfo = "C:\\Users\\DesmondBellinger\\OneDrive - Solvus Global\\Documents\\Azure Arc Sandbox\\TestConfig.ps1::5::5::Computer";
 ConfigurationName = "TestConfig";
};
instance of OMI_ConfigurationDocument

                    {
 Version="2.0.0";

                        MinimumCompatibleVersion = "1.0.0";

                        CompatibleVersionAdditionalProperties= {"Omi_BaseResource:ConfigurationName"};

                        Author="DesmondAdmin";

                        GenerationDate="11/01/2023 11:17:44";

                        GenerationHost="SG-00194";

                        Name="TestConfig";

                    };
