/*
@TargetNode='WIN-QVBS4MOVAKD'
@GeneratedBy=DesmondAdmin
@GenerationDate=09/18/2023 17:26:41
@GenerationHost=SG-00194
*/

instance of DSC_Firewall as $DSC_Firewall1ref
{
SourceInfo = "::7::9::Firewall";
 InterfaceType = "RemoteAccess";
 Ensure = "Present";
 Authentication = "Required";
 RemotePort = {
    "3389"
};
 Action = "Allow";
 ModuleVersion = "9.0.0";
 Encryption = "Required";
 Description = "Opens port 3389 to allow a remote user to RDP into the machine";
 Protocol = "TCP";
 Name = "Public";
 Enabled = "True";
 ModuleName = "NetworkingDsc";
 DisplayName = "Enable RDP";
 Direction = "Inbound";
 ResourceID = "[Firewall]Enable_RDP";
 ConfigurationName = "AzureArcConfig";
};
instance of OMI_ConfigurationDocument

                    {
 Version="2.0.0";

                        MinimumCompatibleVersion = "1.0.0";

                        CompatibleVersionAdditionalProperties= {"Omi_BaseResource:ConfigurationName"};

                        Author="DesmondAdmin";

                        GenerationDate="09/18/2023 17:26:41";

                        GenerationHost="SG-00194";

                        Name="AzureArcConfig";

                    };
